// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdHO4Ax7HQIRwtNgQIJATm2fuSBFR4Ty8',
    appId: '1:335938301917:web:bc572f72df7cdcbed41034',
    messagingSenderId: '335938301917',
    projectId: 'mar-ventas-60eee',
    authDomain: 'mar-ventas-60eee.firebaseapp.com',
    storageBucket: 'mar-ventas-60eee.firebasestorage.app',
    measurementId: 'G-6ES6PCMJT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs-sAGIdPW6q_rtIgvMj9Lynes3oscNXg',
    appId: '1:335938301917:android:4346a1f9106467dcd41034',
    messagingSenderId: '335938301917',
    projectId: 'mar-ventas-60eee',
    storageBucket: 'mar-ventas-60eee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6PtMQn0lzoFlNZIAE1YfpUXTOsskL7AQ',
    appId: '1:335938301917:ios:82509e1552160641d41034',
    messagingSenderId: '335938301917',
    projectId: 'mar-ventas-60eee',
    storageBucket: 'mar-ventas-60eee.firebasestorage.app',
    iosBundleId: 'com.example.marventas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6PtMQn0lzoFlNZIAE1YfpUXTOsskL7AQ',
    appId: '1:335938301917:ios:82509e1552160641d41034',
    messagingSenderId: '335938301917',
    projectId: 'mar-ventas-60eee',
    storageBucket: 'mar-ventas-60eee.firebasestorage.app',
    iosBundleId: 'com.example.marventas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdHO4Ax7HQIRwtNgQIJATm2fuSBFR4Ty8',
    appId: '1:335938301917:web:5b5b7762bacc1b6dd41034',
    messagingSenderId: '335938301917',
    projectId: 'mar-ventas-60eee',
    authDomain: 'mar-ventas-60eee.firebaseapp.com',
    storageBucket: 'mar-ventas-60eee.firebasestorage.app',
    measurementId: 'G-CRQ8D5BB4X',
  );
}
